-- Edificar - temas iniciais da página Caminhos

insert into public.themes
  (slug, category, title, description, bible_reference, base_reflection, base_question, base_practice, sort_order)
values
  ('quando-voce-se-afastou-de-deus', 'Deus no centro', 'Quando você se afastou de Deus', 'Um convite para reorganizar o coração sem culpa pesada.', 'Mateus 6:33', 'Nenhuma conquista vale uma vida distante de Deus. Voltar ao centro começa com uma pausa sincera diante do Senhor.', 'O que tem ocupado mais espaço no seu coração do que Deus?', 'Antes de abrir mensagens ou números hoje, ore com sinceridade por alguns minutos.', 10),
  ('quando-a-rotina-engoliu-sua-fe', 'Deus no centro', 'Quando a rotina engoliu sua fé', 'Pausar antes que a pressa decida o tom do dia.', 'Lucas 10:41-42', 'A rotina pode ficar urgente demais e empurrar Deus para as sobras. A pausa devolve ordem ao coração.', 'Sua agenda tem deixado algum espaço real para Deus?', 'Separe um horário simples e protegido para oração hoje.', 20),
  ('quando-precisa-voltar-ao-primeiro-amor', 'Deus no centro', 'Quando precisa voltar ao primeiro amor', 'Lembrar que Deus não deve ficar nas sobras da agenda.', 'Apocalipse 2:4-5', 'Voltar ao primeiro amor não é performance espiritual. É retornar com humildade ao lugar de dependência.', 'O que esfriou no seu relacionamento com Deus?', 'Faça uma oração curta de retorno, sem tentar impressionar ninguém.', 30),

  ('quando-voce-esqueceu-de-agradecer', 'Gratidão', 'Quando você esqueceu de agradecer', 'Reconhecer o que Deus já sustentou até aqui.', '1 Tessalonicenses 5:18', 'Aquilo que hoje parece comum talvez já tenha sido motivo de oração. A gratidão acorda a alma para a bondade de Deus.', 'O que você tem hoje que um dia pediu a Deus?', 'Escreva três motivos de gratidão antes de pedir qualquer coisa.', 40),
  ('quando-uma-bencao-virou-algo-comum', 'Gratidão', 'Quando uma bênção virou algo comum', 'Recuperar sensibilidade para as pequenas misericórdias.', 'Salmo 103:2', 'A rotina pode transformar presentes em paisagem. A fé ensina o coração a lembrar e agradecer.', 'Que bênção você deixou de enxergar como presente?', 'Agradeça por algo simples que costuma passar despercebido.', 50),
  ('quando-voce-so-olha-para-o-que-falta', 'Gratidão', 'Quando você só olha para o que falta', 'Olhar para a vida com humildade e contentamento.', 'Filipenses 4:11-13', 'O coração que olha apenas para a falta perde sensibilidade para o cuidado de Deus no caminho.', 'O que Deus já sustentou que você não tem reconhecido?', 'Antes de reclamar hoje, nomeie uma provisão concreta de Deus.', 60),

  ('quando-sua-familia-so-recebe-seu-cansaco', 'Família', 'Quando sua família só recebe seu cansaço', 'Voltar a estar presente com amor e mansidão.', '1 Timóteo 5:8', 'Trabalhar pela família não substitui presença, escuta e mansidão dentro de casa.', 'Quem perto de você precisa receber mais presença do que justificativas?', 'Separe um tempo sem celular para ouvir alguém da sua família.', 70),
  ('quando-o-trabalho-esta-tomando-tudo', 'Família', 'Quando o trabalho está tomando tudo', 'Reavaliar prioridades diante de Deus.', 'Marcos 8:36', 'O trabalho é importante, mas não pode ocupar o altar do coração. Deus também chama você a cuidar da casa.', 'O que o trabalho tem tomado que deveria ser protegido?', 'Defina um limite claro de trabalho para hoje e honre esse limite.', 80),
  ('quando-quer-liderar-sua-casa-com-amor', 'Família', 'Quando quer liderar sua casa com amor', 'Cuidar da casa antes de tentar vencer o mundo.', 'Josué 24:15', 'A liderança mais importante talvez esteja no modo como você ama, escuta e serve dentro de casa.', 'Sua casa tem recebido seu melhor ou apenas o que sobra?', 'Faça uma atitude prática de cuidado por alguém da sua família.', 90),

  ('quando-o-dinheiro-ocupa-espaco-demais', 'Dinheiro e coração', 'Quando o dinheiro ocupa espaço demais', 'Trabalhar com responsabilidade sem entregar o coração.', 'Mateus 6:24', 'O dinheiro é necessário, mas perigoso quando vira segurança, identidade e senhor do coração.', 'O dinheiro tem sido ferramenta ou tem ocupado o lugar de Deus?', 'Agradeça por algo que Deus te deu e que dinheiro nenhum compra.', 100),
  ('quando-o-resultado-virou-identidade', 'Dinheiro e coração', 'Quando o resultado virou identidade', 'Separar valor pessoal de números e reconhecimento.', 'Colossenses 3:23', 'Resultados importam, mas não definem quem você é diante de Deus. O coração precisa de uma base mais firme.', 'Quem você acredita ser quando os números não vão bem?', 'Ore entregando a Deus sua identidade, não apenas seus resultados.', 110),
  ('quando-a-comparacao-te-domina', 'Dinheiro e coração', 'Quando a comparação te domina', 'Sair da pressa de medir a própria vida pela dos outros.', 'Gálatas 6:4', 'A comparação rouba gratidão e produz ansiedade. Deus forma sua vida em um caminho que não precisa imitar o dos outros.', 'Com quem você tem medido sua própria vida?', 'Evite comparar resultados hoje e pratique uma oração de contentamento.', 120),

  ('quando-voce-precisa-liderar-com-humildade', 'Liderança e caráter', 'Quando você precisa liderar com humildade', 'Ser exemplo antes de cobrar dos outros.', 'Marcos 10:45', 'A liderança que Deus forma não usa pessoas como degraus. Ela serve, corrige com mansidão e age com caráter.', 'Seu jeito de liderar tem produzido paz ou apenas pressão?', 'Converse com alguém hoje com clareza, mansidão e respeito.', 130),
  ('quando-esta-tratando-pessoas-com-impaciencia', 'Liderança e caráter', 'Quando está tratando pessoas com impaciência', 'Permitir que a fé alcance o jeito de liderar.', 'Provérbios 15:1', 'A pressão pode endurecer a fala. Mas a fé precisa alcançar também o tom, a escuta e a maneira de corrigir.', 'Quem tem recebido sua pressa em vez da sua mansidão?', 'Antes de corrigir alguém, respire, ore e escolha palavras com cuidado.', 140),
  ('quando-o-orgulho-comeca-a-aparecer', 'Liderança e caráter', 'Quando o orgulho começa a aparecer', 'Voltar ao lugar de servo diante de Deus.', 'Tiago 4:6', 'O orgulho pode se esconder atrás da competência. Deus chama líderes a dependerem Dele com humildade.', 'Onde você tem resistido a reconhecer limites?', 'Peça perdão ou conselho em uma área onde você tem tentado parecer invulnerável.', 150),

  ('quando-tudo-parece-pesado', 'Tribulações', 'Quando tudo parece pesado', 'Respirar, orar e caminhar sem decidir movido pelo medo.', 'Filipenses 4:6-7', 'Deus não pede que você finja leveza. Ele convida você a levar o peso a Ele com sinceridade.', 'Qual peso você está tentando carregar sozinho?', 'Pare por três minutos, ore e respire antes da próxima decisão.', 160),
  ('quando-voce-esta-ansioso', 'Tribulações', 'Quando você está ansioso', 'Entregar a pressa e buscar a paz que vem de Deus.', '1 Pedro 5:7', 'A ansiedade tenta governar cada decisão. A oração não apaga responsabilidades, mas reorganiza o coração.', 'Que medo está tentando dirigir suas escolhas?', 'Nomeie sua preocupação diante de Deus e entregue uma ação pequena e responsável para hoje.', 170),
  ('quando-esta-com-medo', 'Tribulações', 'Quando está com medo', 'Confiar sem fingir que a dor não existe.', 'Isaías 41:10', 'A fé não exige negar o medo. Ela convida você a não deixar o medo ocupar o lugar de Deus.', 'O que você faria diferente se não estivesse decidindo apenas pelo medo?', 'Ore pedindo coragem e converse com alguém maduro antes de agir.', 180),

  ('antes-de-uma-decisao-importante', 'Clareza e decisões', 'Antes de uma decisão importante', 'Orar, avaliar e procurar conselhos maduros.', 'Tiago 1:5', 'Nem toda decisão precisa nascer da pressa. Sabedoria começa quando o coração reconhece seus limites.', 'Esta decisão nasce de sabedoria ou de ansiedade?', 'Escreva a decisão, ore e busque conselho maduro antes de movimentos definitivos.', 190),
  ('quando-voce-esta-confuso', 'Clareza e decisões', 'Quando você está confuso', 'Buscar sabedoria sem pressa e sem orgulho.', 'Provérbios 3:5-6', 'Confusão não precisa virar desespero. Deus chama você a confiar, avaliar e caminhar com humildade.', 'O que você está tentando resolver sem pedir ajuda?', 'Liste o que sabe, o que não sabe e quem pode te aconselhar com maturidade.', 200),
  ('quando-esta-tentando-controlar-tudo-sozinho', 'Clareza e decisões', 'Quando está tentando controlar tudo sozinho', 'Reconhecer limites e depender de Deus com humildade.', 'Salmo 127:1', 'Controle pode parecer responsabilidade, mas às vezes revela medo. Deus convida você a trabalhar sem idolatrar o controle.', 'Onde você está confundindo responsabilidade com controle absoluto?', 'Entregue a Deus uma preocupação que você não consegue controlar hoje.', 210)
on conflict (slug) do update
set category = excluded.category,
    title = excluded.title,
    description = excluded.description,
    bible_reference = excluded.bible_reference,
    base_reflection = excluded.base_reflection,
    base_question = excluded.base_question,
    base_practice = excluded.base_practice,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();
